import { useRef, useState } from 'react'
import { BsCamera } from 'react-icons/bs'
import { BASE_API_URL } from '../../utils/constante';
import axios from 'axios';
import { useNavigate } from 'react-router-dom';
import { QRCode } from 'react-qrcode-logo';
import NavBar from '../NavBar';
import Logo from './logo.png';
import { ChevronLeft } from 'lucide-react';

const Form = () => {
    // Ref to access the canvas element generated by the library 
    const qrCodeRef = useRef(null);

    const coverRef = useRef();
    const profileRef = useRef();
    const logoRef = useRef();

    const [profile, setProfile] = useState(null);
    const [cover, setCover] = useState(null);
    const [logo, setLogo] = useState(null);
    const [qrData, setQrData] = useState("");
    const [name, setName] = useState("");
    const [profession, setProfession] = useState("");
    const [company, setCompany] = useState("");
    const [bio, setBio] = useState("");
    const [phoneNumber, setPhoneNumber] = useState("");
    const [email, setEmail] = useState("");
    const [address, setAddress] = useState("");
    const [websiteTitle, setWebsiteTitle] = useState("");
    const [websiteLink, setWebsiteLink] = useState("");
    const [facebookTitle, setFacebookTitle] = useState("");
    const [facebookLink, setFacebookLink] = useState("");
    const [whatsappTitle, setWhatsappTitle] = useState("");
    const [whatsappLink, setWhatsappLink] = useState("");
    const [instagramTitle, setInstagramTitle] = useState("");
    const [instagramLink, setInstagramLink] = useState("");
    const [linkedInTitle, setLinkedInTitle] = useState("");
    const [linkedInLink, setLinkedInLink] = useState("");
    const [xTitle, setXTitle] = useState("");
    const [xLink, setXLink] = useState("");
    const [tiktokTitle, setTiktokTitle] = useState("");
    const [tiktokLink, setTiktokLink] = useState("");
    const [youtubeTitle, setYoutubeTitle] = useState("");
    const [youtubeLink, setYoutubeLink] = useState("");

    const [loading, setLoading] = useState(false);

    const navigate = useNavigate();

    const handleSubmit = async () => {
        setLoading(true)

        const formData = {
            "name": name,
            "profession": profession,
            "logoPicture": logo,
            "company": company,
            "bio": bio,
            "phoneNumber": phoneNumber,
            "email": email,
            "address": address,
            "websiteTitle": websiteTitle,
            "websiteLink": websiteLink,
            "facebookTitle": facebookTitle,
            "facebookLink": facebookLink,
            "whatsappTitle": whatsappTitle,
            "whatsappLink": whatsappLink,
            "instagramTitle": instagramTitle,
            "instagramLink": instagramLink,
            "linkedinTitle": linkedInTitle,
            "linkedinLink": linkedInLink,
            "xTitle": xTitle,
            "xLink": xLink,
            "tiktokTitle": tiktokTitle,
            "tiktokLink": tiktokLink,
            "youtubeTitle": youtubeTitle,
            "youtubeLink": youtubeLink,
        }

        // Fonction utilitaire pour convertir Data URL en Blob
        function dataURLtoFile(dataurl, filename) {
            const arr = dataurl.split(',');
            const mime = arr[0].match(/:(.*?);/)[1];
            const bstr = atob(arr[1]);
            let n = bstr.length;
            const u8arr = new Uint8Array(n);
            
            while (n--) {
                u8arr[n] = bstr.charCodeAt(n);
            }
            
            return new File([u8arr], filename, { type: mime });
        }
        console.log(formData);
        try {
            const response = await axios.post(BASE_API_URL+"/api/post/create", formData)
            console.log(response?.data);
            
            if(response?.data){
                setQrData(`https://card.lacarteboss.com/${response?.data?._id}`);

                if(profile){
                    const profileData = new FormData();
                    profileData.append('profilePicture', profile)
                    await axios.put(BASE_API_URL+"/api/post/picture/"+response?.data?._id, profileData)
                    .then(res => console.log(res))
                    .catch(err => console.log(err))
                }

                if(logo){
                    const logoData = new FormData();
                    logoData.append('logoPicture', logo)
                    await axios.put(BASE_API_URL+"/api/post/logo/"+response?.data?._id, logoData)
                    .then(res => console.log(res))
                    .catch(err => console.log(err))
                }
                
                if(cover){
                    const coverData = new FormData();
                    coverData.append('coverPicture', cover)
                    await axios.put(BASE_API_URL+"/api/post/cover/"+response?.data?._id, coverData)
                    .then(res => console.log(res))
                    .catch(err => console.log(err))
                }
                
                const canvas = qrCodeRef.current.querySelector('canvas');
                const qrCodeDataUrl = canvas.toDataURL('image/png');
                const qrCodeFile = dataURLtoFile(qrCodeDataUrl, 'qrcode.png');
                console.log(qrCodeFile);
                const qrCodeData = new FormData();
                qrCodeData.append('data', qrData)
                qrCodeData.append('qrCode', qrCodeFile)
                await axios.put(BASE_API_URL+"/api/post/qrcode/"+response?.data?._id, qrCodeData)
                .then(res => console.log(res))
                .catch(err => console.log(err))
            }

            setLoading(false)
            navigate('/dashboard')
        } catch (err) {
            console.log(err);
            setLoading(false)
        }   
    }

    return (
        <div className="container p-5 lg:max-w-3/5 mx-auto">
            <NavBar />
            <div className="flex items-center mb-3">
                <ChevronLeft
                    className="h-7 w-7 p-1 cursor-pointer" 
                    onClick={()=>navigate(-1)}
                />
                <h2 className='font-medium text-xl'>Nouvelle carte</h2>
            </div>
            {/* <form method='post'  > */}
                {/* Images */}
                <div className="relative">
                    <img src={cover?URL.createObjectURL(cover):"/no-banner.png"} className='border' style={{objectFit: 'cover', width: '100%', height: '200px'}} alt="" />
                    <div className="flex justify-center items-center p-1 border border-gray-300 rounded-full bg-white absolute right-5 top-3 cursor-pointer" onClick={() => {coverRef.current.click()}}>
                        <BsCamera />
                    </div>
                    <div className='hidden'>
                        <input type="file" name="cover" id='cover' ref={coverRef} accept="image/*" onChange={(e)=>setCover(e.target.files[0])} />
                    </div>
                </div>
                <div className="relative"  style={{ width: '140px', height: '140px', margin: '-50px 10px 0px'}}>
                    <img src={profile?URL.createObjectURL(profile):"/no-img.jpg"} className='border' style={{ width: '140px', height: '140px', objectFit: 'cover', border: '5px solid #ddd', borderRadius: '50%', margin: '-40px 10px 0px'}} alt="" />
                    <div className="flex justify-center items-center p-1 border rounded-full bg-white absolute right-0 bottom-0 cursor-pointer" onClick={() => {profileRef.current.click()}}>
                        <BsCamera />
                    </div>
                    <div className='hidden'>
                        <input type="file" name="profile" id='profile' ref={profileRef} accept="image/*" onChange={(e)=>setProfile(e.target.files[0])} />
                    </div>
                </div>
                <div className="relative"  style={{ width: '65px', height: '65px', margin: '-90px 0px 0px 120px'}}>
                    <img src={logo?URL.createObjectURL(logo):"/no-img.jpg"} className='border' style={{ width: '65px', height: '65px', objectFit: 'cover', border: '3px solid #ddd', borderRadius: '50%', margin: '-40px 10px 0px'}} alt="" />
                    <div className="flex justify-center items-center p-1 border border-gray-400 rounded-full bg-white absolute -right-2 bottom-0 cursor-pointer" onClick={() => {logoRef.current.click()}}>
                        <BsCamera size={10} />
                    </div>
                    <div className='hidden'>
                        <input type="file" name="logoPicture" id='logoPicture' ref={logoRef} accept="image/*" onChange={(e)=>setLogo(e.target.files[0])} />
                    </div>
                </div>

                <p className='text-lg mt-5 p-2'><b>Identité</b></p>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-2">
                    <input type="text" name="name" id="name"
                        className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0'
                        onChange={(e)=>setName(e.target.value)} 
                        placeholder='Nom' 
                        required
                    />
                    <input type="text" name="profession" id="profession"
                        className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0'
                        onChange={(e)=>setProfession(e.target.value)}
                        placeholder='Titre du travail'  
                        required
                    />
                    <input type="text" name="company" id="company"
                        className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0'
                        onChange={(e)=>setCompany(e.target.value)}
                        placeholder='company' 
                    />
                </div>
                <textarea name="bio" id="bio" rows={5}
                    className='block w-full mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-xl focus:outline-0'
                    onChange={(e)=>setBio(e.target.value)}
                    placeholder='Biographie'  
                >
                </textarea>

                <p className='text-lg mt-5 p-2'><b>Contacts</b></p>
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-2">
                    <input type="text" name="phoneNumber" id="phoneNumber"
                        className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0'
                        onChange={(e)=>setPhoneNumber(e.target.value)}
                        placeholder='Numéro de téléphone' 
                    />
                    <input type="email" name="email" id="email"
                        className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0'
                        onChange={(e)=>setEmail(e.target.value)}
                        placeholder='Adresse email' 
                    />
                    <input type="text" name="address" id="address"
                        className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0'
                        onChange={(e)=>setAddress(e.target.value)}
                        placeholder='Adresse physique' 
                    />
                </div>

                {/* Liens */}
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-2">
                    <div className="website">
                        <p className='text-lg mt-5 p-2'><b>Site web</b></p>                
                        <input type="text" name="websiteTitle" id="websiteTitle"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setWebsiteTitle(e.target.value)}
                            placeholder='Titre' 
                        />
                        <input type="text" name="websiteLink" id="websiteLink"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setWebsiteLink(e.target.value)}
                            placeholder='Lien' 
                        />
                    </div>
                    <div className="facebook">
                        <p className='text-lg mt-5 p-2'><b>Facebook</b></p>                
                        <input type="text" name="facebookTitle" id="facebookTitle"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setFacebookTitle(e.target.value)}
                            placeholder='Titre' 
                        />
                        <input type="text" name="facebookLink" id="facebookLink"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setFacebookLink(e.target.value)}
                            placeholder='Lien' 
                        />
                    </div>
                    <div className="whatsapp">
                        <p className='text-lg mt-5 p-2'><b>Whatsapp</b></p>                
                        <input type="text" name="whatsappTitle" id="whatsappTitle"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setWhatsappTitle(e.target.value)}
                            placeholder='Titre' 
                        />
                        <input type="text" name="whatsappLink" id="whatsappLink"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setWhatsappLink(e.target.value)}
                            placeholder='Lien' 
                        />
                    </div>
                    <div className="instagram">
                        <p className='text-lg mt-5 p-2'><b>Instagram</b></p>                
                        <input type="text" name="instagramTitle" id="instagramTitle"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setInstagramTitle(e.target.value)}
                            placeholder='Titre' 
                        />
                        <input type="text" name="instagramLink" id="instagramLink"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setInstagramLink(e.target.value)}
                            placeholder='Lien' 
                        />
                    </div>
                    <div className="linkedin">
                        <p className='text-lg mt-5 p-2'><b>Linkedin</b></p>                
                        <input type="text" name="linkedinTitle" id="linkedinTitle"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setLinkedInTitle(e.target.value)}
                            placeholder='Titre' 
                        />
                        <input type="text" name="linkedinLink" id="linkedinLink"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setLinkedInLink(e.target.value)}
                            placeholder='Lien' 
                        />
                    </div>
                    <div className="x">
                        <p className='text-lg mt-5 p-2'><b>X</b></p>                
                        <input type="text" name="xTitle" id="xTitle"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setXTitle(e.target.value)}
                            placeholder='Titre' 
                        />
                        <input type="text" name="xLink" id="xLink"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setXLink(e.target.value)}
                            placeholder='Lien' 
                        />
                    </div>
                    <div className="tiktok">
                        <p className='text-lg mt-5 p-2'><b>Tiktok</b></p>                
                        <input type="text" name="tiktokTitle" id="tiktokTitle"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setTiktokTitle(e.target.value)}
                            placeholder='Titre' 
                        />
                        <input type="text" name="tiktokLink" id="tiktokLink"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setTiktokLink(e.target.value)}
                            placeholder='Lien' 
                        />
                    </div>
                    <div className="youtube">
                        <p className='text-lg mt-5 p-2'><b>Youtube</b></p>                
                        <input type="text" name="youtubeTitle" id="youtubeTitle"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setYoutubeTitle(e.target.value)}
                            placeholder='Titre' 
                        />
                        <input type="text" name="youtubeLink" id="youtubeLink"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setYoutubeLink(e.target.value)}
                            placeholder='Lien' 
                        />
                    </div>
                </div>
                {
                    !loading 
                    ? <button 
                        type='submit'
                        onClick={handleSubmit}
                        className='block lg:mt-4 mb-5 bg-gray-700 hover:bg-gray-900 text-white lg:py-3 py-2 px-4 rounded-full w-72 cursor-pointer'
                    >
                        Enregistrer 
                    </button>
                    : <button 
                        type='button'
                        className='block lg:mt-4 mb-5 bg-gray-400 text-gray-600 lg:py-3 py-2 px-4 rounded-full w-72 cursor-pointer'
                    >
                        Chargement...
                    </button>
                }
            {/* </form> */}

            <div style={{ marginTop: '20px', display: 'none' }} ref={qrCodeRef}>
                {/* The react-qrcode-logo component with logo prop */}
                <QRCode 
                    value={qrData} 
                    size={400} // Size of the entire QR code in pixels
                    // logoImage={Logo} // Pass the imported logo image source
                    logoWidth={120} // Width of the logo inside the QR code
                    logoHeight={100} // Height of the logo inside the QR code
                    logoPadding={5} // Adds a white padding around the logo area
                    fgColor={'#26265eff'}
                    removeQrCodeBehindLogo={false} // Ensures clean display by removing underlying QR modules
                /> 
            </div>
        </div>
    )
}

export default Form
