import { useRef, useState } from 'react'
import { BsCamera } from 'react-icons/bs'
import { BASE_API_URL } from '../../utils/constante';
import { useNavigate } from 'react-router-dom';
import QRCode from 'qrcode';
import NavBar from '../NavBar';
import Logo from './logo.png';
import { ChevronLeft } from 'lucide-react';
// import { compressImage } from '../../utils/compress';
import api from '../../utils/axiosConfig';
import { generate_string_aléatoire } from '../../utils/generate_string';

const Form = () => {
    // Ref to access the canvas element generated by the library 
    const coverRef = useRef();
    const profileRef = useRef();
    const logoRef = useRef();

    const [profile, setProfile] = useState(null);
    const [cover, setCover] = useState(null);
    const [logo, setLogo] = useState(null);
    const [name, setName] = useState("");
    const [profession, setProfession] = useState("");
    const [company, setCompany] = useState("");
    const [bio, setBio] = useState("");
    const [phoneNumber, setPhoneNumber] = useState("");
    const [email, setEmail] = useState("");
    const [address, setAddress] = useState("");
    const [websiteTitle, setWebsiteTitle] = useState("");
    const [websiteLink, setWebsiteLink] = useState("");
    const [facebookTitle, setFacebookTitle] = useState("");
    const [facebookLink, setFacebookLink] = useState("");
    const [whatsappTitle, setWhatsappTitle] = useState("");
    const [whatsappLink, setWhatsappLink] = useState("");
    const [instagramTitle, setInstagramTitle] = useState("");
    const [instagramLink, setInstagramLink] = useState("");
    const [linkedInTitle, setLinkedInTitle] = useState("");
    const [linkedInLink, setLinkedInLink] = useState("");
    const [xTitle, setXTitle] = useState("");
    const [xLink, setXLink] = useState("");
    const [tiktokTitle, setTiktokTitle] = useState("");
    const [tiktokLink, setTiktokLink] = useState("");
    const [youtubeTitle, setYoutubeTitle] = useState("");
    const [youtubeLink, setYoutubeLink] = useState("");

    const [loading, setLoading] = useState(false);

    const navigate = useNavigate();

    const card_id = generate_string_aléatoire(10);
    
    const handleSubmit = async () => {
        setLoading(true)
        const user = JSON.parse(localStorage.getItem('user'))
        
        const formData = new FormData();
        formData.append('card_id', card_id);
        formData.append('full_name', name);
        formData.append('profession', profession);
        formData.append('company', company);
        formData.append('bio', bio);
        formData.append('phone_number', phoneNumber);
        formData.append('email', email);
        formData.append('address', address);
        formData.append('website_title', websiteTitle);
        formData.append('website_link', websiteLink);
        formData.append('facebook_title', facebookTitle);
        formData.append('facebook_link', facebookLink);
        formData.append('whatsapp_title', whatsappTitle);
        formData.append('whatsapp_link', whatsappLink);
        formData.append('instagram_title', instagramTitle);
        formData.append('instagram_link', instagramLink);
        formData.append('linkedin_title', linkedInTitle);
        formData.append('linkedin_link', linkedInLink);
        formData.append('x_title', xTitle);
        formData.append('x_link', xLink);
        formData.append('tiktok_title', tiktokTitle);
        formData.append('tiktok_link', tiktokLink);
        formData.append('youtube_title', youtubeTitle);
        formData.append('youtube_link', youtubeLink);
        formData.append('created_by', user.id);
        
        if(profile){
            // const compressedProfile = await compressImage(profile);
            formData.append('profile_picture', profile);
        }
        if(cover){
            // const compressedCover = await compressImage(cover);
            formData.append('cover_picture', cover);
        }
        if(logo){
            // const compressedLogo = await compressImage(logo);
            formData.append('company_logo', logo);
        }
        
        // Fonction utilitaire pour convertir Data URL en Blob
        function dataURLtoFile(dataurl, filename) {
            const arr = dataurl.split(',');
            const mime = arr[0].match(/:(.*?);/)[1];
            const bstr = atob(arr[1]);
            let n = bstr.length;
            const u8arr = new Uint8Array(n);
            
            while (n--) {
                u8arr[n] = bstr.charCodeAt(n);
            }
            
            return new File([u8arr], filename, { type: mime });
        }
        
        try {
            const response = await api.post(BASE_API_URL+"/api/cards/", formData)            
            if(response?.data){
                // Générer le QR code en tant que Data URL
                const qrDataURL = await QRCode.toDataURL(
                    `https://card.lacarteboss.com/card/${card_id}`, // Utilisez votre URL de production
                    // `https://127.0.0.1:8000/card/${card_id}`, // Utilisez votre URL de production
                    {
                        width: 400,
                        margin: 2,
                        color: {
                        dark: '#26265EFF',
                        light: '#FFFFFFFF'
                        }
                    }
                );

                // Convertir Data URL en File
                const qrCodeFile = dataURLtoFile(qrDataURL, `${card_id}.png`);
                
                // Mettre à jour avec le QR code
                const qrCodeData = new FormData();
                qrCodeData.append('card_id', card_id);
                qrCodeData.append('full_name', name);
                qrCodeData.append('profession', profession);
                qrCodeData.append('phone_number', phoneNumber);
                qrCodeData.append('qr_code', qrCodeFile)
                qrCodeData.append('qr_data', `https://card.lacarteboss.com/card/${card_id}`)

                await api.put(BASE_API_URL+"/api/cards/"+card_id+"/", qrCodeData)
            }

            setLoading(false)
            navigate('/dashboard')
        } catch (err) {
            console.log(err);
            setLoading(false)
        }   
    }

    return (
        <div className="container p-5 lg:max-w-3/5 mx-auto">
            <NavBar />
            <div className="flex items-center mb-3">
                <ChevronLeft
                    className="h-7 w-7 p-1 cursor-pointer" 
                    onClick={()=>navigate(-1)}
                />
                <h2 className='font-medium text-xl'>Nouvelle carte</h2>
            </div>
            {/* <form method='post'  > */}
                {/* Images */}
                <div className="relative">
                    <img src={cover?URL.createObjectURL(cover):"/no-banner.png"} className='border' style={{objectFit: 'cover', width: '100%', height: '200px'}} alt="" />
                    <div className="flex justify-center items-center p-1 border border-gray-300 rounded-full bg-white absolute right-5 top-3 cursor-pointer" onClick={() => {coverRef.current.click()}}>
                        <BsCamera />
                    </div>
                    <div className='hidden'>
                        <input type="file" name="cover" id='cover' ref={coverRef} accept="image/*" onChange={(e)=>setCover(e.target.files[0])} />
                    </div>
                </div>
                <div className="relative"  style={{ width: '140px', height: '140px', margin: '-50px 10px 0px'}}>
                    <img src={profile?URL.createObjectURL(profile):"/no-img.jpg"} className='border' style={{ width: '140px', height: '140px', objectFit: 'cover', border: '5px solid #ddd', borderRadius: '50%', margin: '-40px 10px 0px'}} alt="" />
                    <div className="flex justify-center items-center p-1 border rounded-full bg-white absolute right-0 bottom-0 cursor-pointer" onClick={() => {profileRef.current.click()}}>
                        <BsCamera />
                    </div>
                    <div className='hidden'>
                        <input type="file" name="profile" id='profile' ref={profileRef} accept="image/*" onChange={(e)=>setProfile(e.target.files[0])} />
                    </div>
                </div>
                <div className="relative"  style={{ width: '65px', height: '65px', margin: '-90px 0px 0px 120px'}}>
                    <img src={logo?URL.createObjectURL(logo):"/no-img.jpg"} className='border' style={{ width: '65px', height: '65px', objectFit: 'cover', border: '3px solid #ddd', borderRadius: '50%', margin: '-40px 10px 0px'}} alt="" />
                    <div className="flex justify-center items-center p-1 border border-gray-400 rounded-full bg-white absolute -right-2 bottom-0 cursor-pointer" onClick={() => {logoRef.current.click()}}>
                        <BsCamera size={10} />
                    </div>
                    <div className='hidden'>
                        <input type="file" name="logoPicture" id='logoPicture' ref={logoRef} accept="image/*" onChange={(e)=>setLogo(e.target.files[0])} />
                    </div>
                </div>

                <p className='text-lg mt-5 p-2'><b>Identité</b></p>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-2">
                    <input type="text" name="name" id="name"
                        className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0'
                        onChange={(e)=>setName(e.target.value)} 
                        placeholder='Nom' 
                        required
                    />
                    <input type="text" name="profession" id="profession"
                        className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0'
                        onChange={(e)=>setProfession(e.target.value)}
                        placeholder='Titre du travail'  
                        required
                    />
                    <input type="text" name="company" id="company"
                        className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0'
                        onChange={(e)=>setCompany(e.target.value)}
                        placeholder='company' 
                    />
                </div>
                <textarea name="bio" id="bio" rows={5}
                    className='block w-full mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-xl focus:outline-0'
                    onChange={(e)=>setBio(e.target.value)}
                    placeholder='Biographie'  
                >
                </textarea>

                <p className='text-lg mt-5 p-2'><b>Contacts</b></p>
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-2">
                    <input type="text" name="phoneNumber" id="phoneNumber"
                        className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0'
                        onChange={(e)=>setPhoneNumber(e.target.value)}
                        placeholder='Numéro de téléphone' 
                        required
                    />
                    <input type="email" name="email" id="email"
                        className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0'
                        onChange={(e)=>setEmail(e.target.value)}
                        placeholder='Adresse email' 
                    />
                    <input type="text" name="address" id="address"
                        className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0'
                        onChange={(e)=>setAddress(e.target.value)}
                        placeholder='Adresse physique' 
                    />
                </div>

                {/* Liens */}
                <div className="grid grid-cols-1 lg:grid-cols-3 gap-2">
                    <div className="website">
                        <p className='text-lg mt-5 p-2'><b>Site web</b></p>                
                        <input type="text" name="websiteTitle" id="websiteTitle"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setWebsiteTitle(e.target.value)}
                            placeholder='Titre' 
                        />
                        <input type="text" name="websiteLink" id="websiteLink"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setWebsiteLink(e.target.value)}
                            placeholder='Lien' 
                        />
                    </div>
                    <div className="facebook">
                        <p className='text-lg mt-5 p-2'><b>Facebook</b></p>                
                        <input type="text" name="facebookTitle" id="facebookTitle"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setFacebookTitle(e.target.value)}
                            placeholder='Titre' 
                        />
                        <input type="text" name="facebookLink" id="facebookLink"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setFacebookLink(e.target.value)}
                            placeholder='Lien' 
                        />
                    </div>
                    <div className="whatsapp">
                        <p className='text-lg mt-5 p-2'><b>Whatsapp</b></p>                
                        <input type="text" name="whatsappTitle" id="whatsappTitle"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setWhatsappTitle(e.target.value)}
                            placeholder='Titre' 
                        />
                        <input type="text" name="whatsappLink" id="whatsappLink"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setWhatsappLink(e.target.value)}
                            placeholder='Lien' 
                        />
                    </div>
                    <div className="instagram">
                        <p className='text-lg mt-5 p-2'><b>Instagram</b></p>                
                        <input type="text" name="instagramTitle" id="instagramTitle"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setInstagramTitle(e.target.value)}
                            placeholder='Titre' 
                        />
                        <input type="text" name="instagramLink" id="instagramLink"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setInstagramLink(e.target.value)}
                            placeholder='Lien' 
                        />
                    </div>
                    <div className="linkedin">
                        <p className='text-lg mt-5 p-2'><b>Linkedin</b></p>                
                        <input type="text" name="linkedinTitle" id="linkedinTitle"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setLinkedInTitle(e.target.value)}
                            placeholder='Titre' 
                        />
                        <input type="text" name="linkedinLink" id="linkedinLink"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setLinkedInLink(e.target.value)}
                            placeholder='Lien' 
                        />
                    </div>
                    <div className="x">
                        <p className='text-lg mt-5 p-2'><b>X</b></p>                
                        <input type="text" name="xTitle" id="xTitle"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setXTitle(e.target.value)}
                            placeholder='Titre' 
                        />
                        <input type="text" name="xLink" id="xLink"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setXLink(e.target.value)}
                            placeholder='Lien' 
                        />
                    </div>
                    <div className="tiktok">
                        <p className='text-lg mt-5 p-2'><b>Tiktok</b></p>                
                        <input type="text" name="tiktokTitle" id="tiktokTitle"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setTiktokTitle(e.target.value)}
                            placeholder='Titre' 
                        />
                        <input type="text" name="tiktokLink" id="tiktokLink"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setTiktokLink(e.target.value)}
                            placeholder='Lien' 
                        />
                    </div>
                    <div className="youtube">
                        <p className='text-lg mt-5 p-2'><b>Youtube</b></p>                
                        <input type="text" name="youtubeTitle" id="youtubeTitle"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setYoutubeTitle(e.target.value)}
                            placeholder='Titre' 
                        />
                        <input type="text" name="youtubeLink" id="youtubeLink"
                            className='block mb-5 bg-gray-300 py-2 lg:py-3 px-4 rounded-full focus:outline-0 w-full'
                            onChange={(e)=>setYoutubeLink(e.target.value)}
                            placeholder='Lien' 
                        />
                    </div>
                </div>
                {
                    !loading 
                    ? <button 
                        type='submit'
                        onClick={handleSubmit}
                        className='block lg:mt-4 mb-5 bg-gray-700 hover:bg-gray-900 text-white lg:py-3 py-2 px-4 rounded-full w-72 cursor-pointer'
                    >
                        Enregistrer 
                    </button>
                    : <button 
                        type='button'
                        className='block lg:mt-4 mb-5 bg-gray-400 text-gray-600 lg:py-3 py-2 px-4 rounded-full w-72 cursor-pointer'
                    >
                        Chargement...
                    </button>
                }
            {/* </form> */}
        </div>
    )
}

export default Form
